using C_Basics.DBDataContext;
using C_Basics.DBDataContext.EntityFramework;
using C_Basics.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace C_Basics.Linq
{
    public static class IEnumarableCollection
    {
        public static void TestIEnurambleCollection()
        {
            using (CSharpDataContext DBContext = new CSharpDataContext())
            {
                //To See What SQL Generated By Entity Framework
               // DBContext.Database.Log = Console.Write;
                //Fetch the Top 2 Records from the Students Database table where Gender = Male
                IEnumerable<Product> listProducts = DBContext.Products.Where(x => x.ProductName == "Male");
                listProducts = listProducts.Take(2);
                Console.WriteLine("Top 2 Student Where Gender = Male");
                foreach (var prd in listProducts)
                {
                    Console.WriteLine(prd.ProductName + " " + prd.Quantity);
                }
            }
        }
    }
}
